---
- name: Install web content
  vars:
    ansible_ssh_extra_args: "-l {{ ansible_ssh_user }}"
  synchronize:
    src: "{{ svxportal_src_dir }}/"
    dest: "{{ svxportal_html_dir }}/"
    archive: no
    delete: yes
    links: yes
    owner: no
    group: no
    perms: yes
    times: yes
    recursive: yes
    set_remote_user: no
    use_ssh_args: yes
    rsync_opts:
      - "--exclude=.*"
      - "--exclude=config.php"
      - "--exclude=/svxrecording"
      - "--exclude=/README.md"

- name: Create audio recoring dir
  file:
    path: "{{ svxportal_recording_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ svxportal_html_dir }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - src: "config.php.j2"
      dest: "config.php"
    - src: "proxy-config.php.j2"
      dest: "{{ svxportal_proxy_dir }}config.php"

- name: Install the SvxPortal Apache site config files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apache2/sites-available/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache
  with_items:
    - 001-svxportal.conf
    - 002-svxportal-ssl.conf

- name: Disable the default Apache site
  command: /usr/sbin/a2dissite 000-default
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - restart apache
  when: svxportal_disable_default_site

- name: Enable the SvxPortal Apache site
  command: /usr/sbin/a2ensite 001-svxportal
  args:
    creates: /etc/apache2/sites-enabled/001-svxportal.conf
  notify:
    - restart apache

- name: Enable SSL if correctly configured (pre TLS setup)
  include_tasks: setup-web-enable-ssl-site.yml

- name: Ensure that the http server is started
  service:
    name: "{{ svxportal_http_service }}"
    state: started
    enabled: yes

- name: Set up TLS for the webserver
  include_tasks: setup-web-tls-certificates.yml

- name: Enable SSL if correctly configured (post TLS setup)
  include_tasks: setup-web-enable-ssl-site.yml
