---
- name: Ensure that all certificate paths exist
  file:
    name: "{{ item | dirname }}"
    state: directory
  with_items:
    - "{{ svxportal_tls_key_path }}"
    - "{{ svxportal_tls_csr_path }}"
    - "{{ svxportal_tls_crt_path }}"
  loop_control:
    label: "{{ item | dirname }}"

- name: Generate a private key for the certificate
  openssl_privatekey:
    path: "{{ svxportal_tls_key_path }}"
    type: RSA
    size: 4096
    owner: root
    group: ssl-cert
    mode: 0640
    state: present

- name: Generate a certificate signing request
  openssl_csr:
    path: "{{ svxportal_tls_csr_path }}"
    privatekey_path: "{{ svxportal_tls_key_path }}"
    common_name: "{{ svxportal_public_hostname }}"
    #use_common_name_for_san: yes
    subject_alt_name: "DNS:{{ svxportal_public_hostname }}"
    #force: yes
    digest: sha256
    owner: root
    group: root
    mode: 0644
    state: present

- block:
    - name: Load ACME accout key
      include_vars: "{{ svxportal_tls_acme_key_vault_path }}"
  rescue:
    - name: Generate an ACME account key
      vars:
        ansible_become: false
      openssl_privatekey:
        path: "{{ svxportal_tls_acme_key_path }}"
        type: RSA
        size: 4096
        #owner: root
        #group: ssl-cert
        mode: 0600
        state: present
      delegate_to: localhost

    - name: Manually encrypt the ACME account key
      pause:
        prompt: |-
          Run the following command manually, in another terminal, to create an
          encrypted version of the ACME account key.

            ansible-vault encrypt_string --stdin-name svxportal_tls_acme_account_key < {{ svxportal_tls_acme_key_path }} > {{ svxportal_tls_acme_key_vault_path }} && rm -f {{ svxportal_tls_acme_key_path }}

            When done, press ENTER to continue or Ctrl-C to abort

    - name: Load ACME accout key
      include_vars: "{{ svxportal_tls_acme_key_vault_path }}"

- name: Ensure ACME account is created and up to date
  vars:
    ansible_become: false
  acme_account:
    account_key_content: "{{ svxportal_tls_acme_account_key }}"
    #account_key_src: "{{ svxportal_tls_acme_key_path }}"
    acme_directory: "{{ svxportal_tls_acme_directory }}"
    acme_version: 2
    allow_creation: yes
    contact:
      "{{ svxportal_tls_acme_contact }}"
    state: present
    terms_agreed: "{{ svxportal_tls_acme_terms_agreed }}"
  delegate_to: localhost
  run_once: true

- name: Request cert signing if cert is nonexistent or if it's about to expire
  vars:
    ansible_become: false
  acme_certificate:
    acme_directory: "{{ svxportal_tls_acme_directory }}"
    acme_version: 2
    account_key_content: "{{ svxportal_tls_acme_account_key }}"
    #account_key_src: {{ svxportal_tls_acme_key }}
    challenge: http-01
    csr: "{{ svxportal_tls_csr_path }}"
    dest: "{{ svxportal_tls_crt_path }}"
    chain_dest: "{{ svxportal_tls_intermediate_path }}"
    #fullchain_dest: "{{ svxportal_tls_fullchain_path }}"
    remaining_days: "{{ svxportal_tls_acme_remaining_days_renew }}"
    modify_account: no
  register: acme_challenge

# FIXME: Make sure that the path to the challenge is safe, that it does not
# point to a directory outside of the webroot and that it does not overwrite
# any files it should not overwrite. What does the ACME standard say about the
# path for the challenge?
# RFC 8555: https://tools.ietf.org/html/rfc8555#section-8.3

#- name: Set up a dummy challenge for testing
#  set_fact:
#    acme_challenge:
#      changed: True
#      challenge_data:
#        sk3w.se:
#          http-01:
#            resource: ".well-known/dummy-challenge/ansible-test-dummy-challenge"
#            resource_value: |
#              This is a dummy challenge used to test the Ansible playbooks
#  tags: devel

- name: Make sure that the challenge directory exist
  vars:
    ansible_become: "{{ svxportal_tls_acme_challenge_become }}"
  file:
    path: "{{ svxportal_tls_acme_challenge_webroot }}/{{ acme_challenge['challenge_data'][svxportal_public_hostname]['http-01']['resource'] | dirname }}"
    owner: "{{ svxportal_tls_acme_challenge_owner | d(omit) }}"
    group: "{{ svxportal_tls_acme_challenge_group | d(omit) }}"
    mode: 0755
    state: directory
  delegate_to: "{{ svxportal_tls_acme_challenge_delegate_to | d(omit) }}"
  when: >-
    acme_challenge is changed and
    svxportal_public_hostname in acme_challenge['challenge_data']

- name: Copy challenge to file
  vars:
    ansible_become: "{{ svxportal_tls_acme_challenge_become }}"
  copy:
    dest: "{{ svxportal_tls_acme_challenge_webroot }}/{{ acme_challenge['challenge_data'][svxportal_public_hostname]['http-01']['resource'] }}"
    content: "{{ acme_challenge['challenge_data'][svxportal_public_hostname]['http-01']['resource_value'] }}"
    owner: "{{ svxportal_tls_acme_challenge_owner | d(omit) }}"
    group: "{{ svxportal_tls_acme_challenge_group | d(omit) }}"
    mode: 0644
  delegate_to: "{{ svxportal_tls_acme_challenge_delegate_to | d(omit) }}"
  when: >-
    acme_challenge is changed and
    svxportal_public_hostname in acme_challenge['challenge_data']

- name: Manually copy challenge to http web root
  pause:
    prompt: |-

      Manually copy the provided challenge to the webroot of the web server
      that serves on port 80 for {{ svxportal_public_hostname }}.

      The whole directory hierachy must be preserved as is.

        {{ svxportal_tls_acme_challenge_webroot }}/{{ acme_challenge['challenge_data'][svxportal_public_hostname]['http-01']['resource'].split('/')[0] }}

      Press ENTER to continue or Ctrl-C to abort
  when: svxportal_tls_acme_challenge_manual

- name: Let the challenge be validated and retrieve the cert and intermediate certificate
  acme_certificate:
    acme_directory: "{{ svxportal_tls_acme_directory }}"
    acme_version: 2
    account_key_content: "{{ svxportal_tls_acme_account_key }}"
    #account_key_src: {{ svxportal_tls_acme_key }}
    challenge: http-01
    csr: "{{ svxportal_tls_csr_path }}"
    dest: "{{ svxportal_tls_crt_path }}"
    chain_dest: "{{ svxportal_tls_intermediate_path }}"
    #fullchain_dest: "{{ svxportal_tls_fullchain_path }}"
    remaining_days: "{{ svxportal_tls_acme_remaining_days_renew }}"
    modify_account: no
    data: "{{ acme_challenge }}"

- name: Clear ACME account key variable
  set_fact:
    svxportal_tls_acme_account_key:
