---
- name: Check if certificate files exist
  stat:
    path: "{{ item }}"
  with_items:
    - "{{ svxportal_tls_key_path }}"
    - "{{ svxportal_tls_crt_path }}"
    - "{{ svxportal_tls_intermediate_path }}"
  register: check_cert_files
  when: svxportal_tls_enable

- name: Set up the tls_enable fact
  set_fact:
    tls_enable: >-
      {{ svxportal_tls_enable and
         (check_cert_files.results | map(attribute='stat.exists') |
         select('equalto', false) | list | length == 0) }}

- name: "Ensure that the Apache SSL module is {{ tls_enable | ternary('en', 'dis') }}abled"
  command: >
    /usr/sbin/a2{{ tls_enable | ternary('en', 'dis') }}mod ssl
  args:
    creates: "{{ tls_enable | ternary('/etc/apache2/mods-enabled/ssl.conf', omit) }}"
    removes: "{{ (not tls_enable) | ternary('/etc/apache2/mods-enabled/ssl.conf', omit) }}"
  notify:
    - restart apache

- name: "Ensure that the SvxPortal Apache SSL site is {{ tls_enable | ternary('en', 'dis') }}abled"
  command: >
    /usr/sbin/a2{{ tls_enable | ternary('en', 'dis') }}site 002-svxportal-ssl
  args:
    creates: "{{ tls_enable | ternary('/etc/apache2/sites-enabled/002-svxportal-ssl.conf', omit) }}"
    removes: "{{ (not tls_enable) | ternary('/etc/apache2/sites-enabled/002-svxportal-ssl.conf', omit) }}"
  notify:
    - restart apache
